var i = 0;


var t = 0;


var className = "Warrior Talents";
var talentPath = "/info/basics/talents/";

tree[i] = "Arms"; i++;
tree[i] = "Fury"; i++;
tree[i] = "Protection"; i++;

i = 0;

talent[i] = [0, "Improved Heroic Strike", 3, 1, 1]; i++;
talent[i] = [0, "Deflection", 5, 2, 1]; i++;
talent[i] = [0, "Improved Rend", 3, 3, 1]; i++;
talent[i] = [0, "Improved Charge", 2, 1, 2]; i++; 
talent[i] = [0, "Tactical Mastery", 5, 2, 2]; i++;
talent[i] = [0, "Improved Thunder Clap", 3, 4, 2]; i++;
talent[i] = [0, "Improved Overpower", 2, 1, 3]; i++;
talent[i] = [0, "Anger Management", 1, 2, 3, [getTalentID("Tactical Mastery"),5]]; i++;
talent[i] = [0, "Deep Wounds", 3, 3, 3, [getTalentID("Improved Rend"),3]]; i++;
talent[i] = [0, "Two-Handed Weapon Specialization", 5, 2, 4]; i++;
talent[i] = [0, "Impale", 2, 3, 4, [getTalentID("Deep Wounds"),3]]; i++;
talent[i] = [0, "Axe Specialization", 5, 1, 5]; i++;
talent[i] = [0, "Sweeping Strikes", 1, 2, 5]; i++;
talent[i] = [0, "Mace Specialization", 5, 3, 5]; i++;
talent[i] = [0, "Sword Specialization", 5, 4, 5]; i++;
talent[i] = [0, "Polearm Specialization", 5, 1, 6]; i++;
talent[i] = [0, "Improved Hamstring", 3, 3, 6]; i++;
talent[i] = [0, "Mortal Strike", 1, 2, 7, [getTalentID("Sweeping Strikes"),1]]; i++;

treeStartStop[t] = i -1;
t++;

//fury talents
talent[i] = [1, "Booming Voice", 5, 2, 1]; i++;
talent[i] = [1, "Cruelty", 5, 3, 1]; i++;
talent[i] = [1, "Improved Demoralizing Shout", 5, 2, 2]; i++;
talent[i] = [1, "Unbridled Wrath", 5, 3, 2]; i++;
talent[i] = [1, "Improved Cleave", 3, 1, 3]; i++;
talent[i] = [1, "Piercing Howl", 1, 2, 3]; i++;
talent[i] = [1, "Blood Craze", 3, 3, 3]; i++;
talent[i] = [1, "Improved Battle Shout", 5, 4, 3]; i++;
talent[i] = [1, "Dual Wield Specialization", 5, 1, 4]; i++;
talent[i] = [1, "Improved Execute", 2, 2, 4]; i++;
talent[i] = [1, "Enrage", 5, 3, 4]; i++;
talent[i] = [1, "Improved Slam", 5, 1, 5]; i++;
talent[i] = [1, "Death Wish", 1, 2, 5]; i++;
talent[i] = [1, "Improved Intercept", 2, 4, 5]; i++;
talent[i] = [1, "Improved Berserker Rage", 2, 1, 6]; i++;
talent[i] = [1, "Flurry", 5, 3, 6, [getTalentID("Enrage"),5]]; i++;
talent[i] = [1, "Bloodthirst", 1, 2, 7, [getTalentID("Death Wish"),1]]; i++;

treeStartStop[t] = i -1;
t++;

//protection talents
talent[i] = [2, "Shield Specialization", 5, 2, 1]; i++;
talent[i] = [2, "Anticipation", 5, 3, 1]; i++;
talent[i] = [2, "Improved Bloodrage", 2, 1, 2]; i++;
talent[i] = [2, "Toughness", 5, 3, 2]; i++;
talent[i] = [2, "Iron Will", 5, 4, 2]; i++;
talent[i] = [2, "Last Stand", 1, 1, 3, [getTalentID("Improved Bloodrage"),2]]; i++;
talent[i] = [2, "Improved Shield Block", 3, 2, 3, [getTalentID("Shield Specialization"),5]]; i++;
talent[i] = [2, "Improved Revenge", 3, 3, 3]; i++;
talent[i] = [2, "Defiance", 5, 4, 3]; i++;
talent[i] = [2, "Improved Sunder Armor", 3, 1, 4]; i++;
talent[i] = [2, "Improved Disarm", 3, 2, 4]; i++;
talent[i] = [2, "Improved Taunt", 2, 3, 4]; i++;
talent[i] = [2, "Improved Shield Wall", 2, 1, 5]; i++;
talent[i] = [2, "Concussion Blow", 1, 2, 5]; i++;
talent[i] = [2, "Improved Shield Bash", 2, 3, 5]; i++;
talent[i] = [2, "One-Handed Weapon Specialization", 5, 3, 6]; i++;
talent[i] = [2, "Shield Slam", 1, 2, 7, [getTalentID("Concussion Blow"),1]]; i++;

treeStartStop[t] = i -1;
t++;

i = 0;


//Arms Talents Begin

//Improved Heroic Strike - Arms
rank[i] = [
"Reduces the cost of your Heroic Strike ability by 1 rage point.",
"Reduces the cost of your Heroic Strike ability by 2 rage points.",
"Reduces the cost of your Heroic Strike ability by 3 rage points."
		];
i++;		
		
//Deflection - Arms
rank[i] = [
"Increases your Parry chance by 1%.",
"Increases your Parry chance by 2%.",
"Increases your Parry chance by 3%.",
"Increases your Parry chance by 4%.",
"Increases your Parry chance by 5%."
		];
i++;		

//Improved Rend - Arms
rank[i] = [
"Increases the bleed damage done by your Rend ability by 15%.",
"Increases the bleed damage done by your Rend ability by 25%.",
"Increases the bleed damage done by your Rend ability by 35%."
		];
i++;		
		
//Improved Charge - Arms 
rank[i] = [
"Increases the amount of rage generated by your Charge ability by 3.",
"Increases the amount of rage generated by your Charge ability by 6."
		];
i++;		

//Tactical Mastery - Arms
rank[i] = [
"You retain up to 5 of your rage points when you change stances.",
"You retain up to 10 of your rage points when you change stances.",
"You retain up to 15 of your rage points when you change stances.",
"You retain up to 20 of your rage points when you change stances.",
"You retain up to 25 of your rage points when you change stances."
		];
i++;		

//Improved Thunder Clap - Arms
rank[i] = [
"Reduces the cost of your Thunder Clap ability by 1 rage point.",
"Reduces the cost of your Thunder Clap ability by 2 rage points.",
"Reduces the cost of your Thunder Clap ability by 4 rage points."
		];
i++;		
		
//Improved Overpower - Arms
rank[i] = [
"Increases the critical strike chance of your Overpower ability by 25%.",
"Increases the critical strike chance of your Overpower ability by 50%."
		];		
i++;		


//Anger Management - Arms	
rank[i] = [ 
"Increases the time required for your Rage to decay while out of combat by 30%."
		];
i++;		


//Deep Wounds - Arms
rank[i] = [
"Your critical strikes cause the opponent to bleed, dealing 20% of your melee weapon's average damage over 12 sec.",
"Your critical strikes cause the opponent to bleed, dealing 40% of your melee weapon's average damage over 12 sec.",
"Your critical strikes cause the opponent to bleed, dealing 60% of your melee weapon's average damage over 12 sec."
		];
i++;		

//Two-Handed Weapon Specialization - Arms
rank[i] = [
"Increases the damage you deal with two-handed melee weapons by 1%.",
"Increases the damage you deal with two-handed melee weapons by 2%.",
"Increases the damage you deal with two-handed melee weapons by 3%.",
"Increases the damage you deal with two-handed melee weapons by 4%.",
"Increases the damage you deal with two-handed melee weapons by 5%."
		];
i++;		

//Impale - Arms	
rank[i] = [
"Increases the critical strike damage bonus of your abilities in Battle, Defensive, and Berserker stance by 10%.",
"Increases the critical strike damage bonus of your abilities in Battle, Defensive, and Berserker stance by 20%."
		];
i++;		

//Axe Specialization - Arms
rank[i] = [
"Increases your chance to get a critical strike with Axes by 1%.",
"Increases your chance to get a critical strike with Axes by 2%.",
"Increases your chance to get a critical strike with Axes by 3%.",
"Increases your chance to get a critical strike with Axes by 4%.",
"Increases your chance to get a critical strike with Axes by 5%."
		];
i++;		

//Sweeping Strikes - Arms	
rank[i] = [
		"30 Rage<br><span style=text-align:left;float:left;>Instant</span><span style=text-align:right;float:right;>30 sec cooldown</span><br>Requires Melee Weapon<br>Requires Battle Stance<br>Your next 5 melee weapon swings strike an additional nearby opponent."
		];
i++;		

//Mace Specialization - Arms	
rank[i] = [
"Gives you a 1% chance to stun your target for 3 sec with a Mace.",
"Gives you a 2% chance to stun your target for 3 sec with a Mace.",
"Gives you a 3% chance to stun your target for 3 sec with a Mace.",
"Gives you a 4% chance to stun your target for 3 sec with a Mace.",
"Gives you a 6% chance to stun your target for 3 sec with a Mace."
		];		
i++;		

//Sword Specialization - Arms				
rank[i] = [
"Gives you a 1% chance to get an extra attack on the same target after dealing damage with your Sword.",
"Gives you a 2% chance to get an extra attack on the same target after dealing damage with your Sword.",
"Gives you a 3% chance to get an extra attack on the same target after dealing damage with your Sword.",
"Gives you a 4% chance to get an extra attack on the same target after dealing damage with your Sword.",
"Gives you a 5% chance to get an extra attack on the same target after dealing damage with your Sword."
		];
i++;		


//Polearm Specialization - Arms
rank[i] = [
"Increases your chance to get a critical strike with Polearms by 1%.",
"Increases your chance to get a critical strike with Polearms by 2%.",
"Increases your chance to get a critical strike with Polearms by 3%.",
"Increases your chance to get a critical strike with Polearms by 4%.",
"Increases your chance to get a critical strike with Polearms by 5%."
		];
i++;



//Improved Hamstring - Arms	
rank[i] = [
"Gives your Hamstring ability a 5% chance to immobilize the target for 5 sec.",
"Gives your Hamstring ability a 10% chance to immobilize the target for 5 sec.",
"Gives your Hamstring ability a 15% chance to immobilize the target for 5 sec."
		];
i++;

//Mortal Strike - Arms
rank[i] = [
		"<span style=text-align:left;float:left;>30 Rage</span><span style=text-align:right;float:right;>5 yd range</span><br><span style=text-align:left;float:left;>Instant</span><span style=text-align:right;float:right;>6 sec cooldown</span><br>Requires Melee Weapon<br>A vicious strike that deals weapon damage plus 85 and wounds the target, reducing the effectiveness of any healing by 50% for 10 sec.<br><br>\
		&nbsp;Trainable Ranks Listed Below:<br>\
		&nbsp;Rank 2: +110 Damage<br>\
		&nbsp;Rank 3: +135 Damage<br>\
		&nbsp;Rank 4: +160 Damage"
		];		
i++;





















//Booming Voice - Fury
rank[i] = [
"Increases the area of effect and duration of your Battle Shout and Demoralizing Shout by 10%.",
"Increases the area of effect and duration of your Battle Shout and Demoralizing Shout by 20%.",
"Increases the area of effect and duration of your Battle Shout and Demoralizing Shout by 30%.",
"Increases the area of effect and duration of your Battle Shout and Demoralizing Shout by 40%.",
"Increases the area of effect and duration of your Battle Shout and Demoralizing Shout by 50%."
		];
i++;		

//Cruelty - Fury
rank[i] = [
"Increases your chance to get a critical strike with melee weapons by 1%.",
"Increases your chance to get a critical strike with melee weapons by 2%.",
"Increases your chance to get a critical strike with melee weapons by 3%.",
"Increases your chance to get a critical strike with melee weapons by 4%.",
"Increases your chance to get a critical strike with melee weapons by 5%."
		];
i++;

//Improved Demoralizing Shout - Fury	
rank[i] = [
"Increases the Attack Power reduction of your Demoralizing Shout by 8%.",
"Increases the Attack Power reduction of your Demoralizing Shout by 16%.",
"Increases the attack power reduction of your Demoralizing Shout by 24%.",
"Increases the Attack Power reduction of your Demoralizing Shout by 32%.",
"Increases the attack power reduction of your Demoralizing Shout by 40%."
		];
i++;		

//Unbridled Wrath - Fury
rank[i] = [
"Gives you a 8% chance to generate an additional Rage point when you deal melee damage with a weapon.",
"Gives you a 16% chance to generate an additional Rage point when you deal melee damage with a weapon.",
"Gives you a 24% chance to generate an additional Rage point when you deal melee damage with a weapon.",
"Gives you a 32% chance to generate an additional Rage point when you deal melee damage with a weapon.",
"Gives you a 40% chance to generate an additional Rage point when you deal melee damage with a weapon."
		];		
i++;		

//Improved Cleave - Fury
rank[i] = [

"Increases the bonus damage done by your Cleave ability by 40%.",
"Increases the bonus damage done by your Cleave ability by 80%.",
"Increases the bonus damage done by your Cleave ability by 120%."
		];
i++;		

//Piercing Howl - Fury
rank[i] = [
		"10 Rage<br>Instant<br>Causes all enemies near the warrior to be dazed, reducing movement speed by 50% for 6 sec."
		];
i++;		

//Blood Craze - Fury	
rank[i] = [
"Regenerates 1% of your total health over 6 sec after being the victim of a critical strike.",
"Regenerates 2% of your total health over 6 sec after being the victim of a critical strike.",
"Regenerates 3% of your total health over 6 sec after being the victim of a critical strike."
		];
i++;		

//Improved Battle Shout - Fury
rank[i] = [
"Increases the Attack Power bonus of your Battle Shout by 5%.",
"Increases the Attack Power bonus of your Battle Shout by 10%.",
"Increases the Attack Power bonus of your Battle Shout by 15%.",
"Increases the Attack Power bonus of your Battle Shout by 20%.",
"Increases the Attack Power bonus of your Battle Shout by 25%."
		];
i++;		

//Dual Wield Specialization - Fury
rank[i] = [
"Increases the damage done by your offhand weapon by 5%.",
"Increases the damage done by your offhand weapon by 10%.",
"Increases the damage done by your offhand weapon by 15%.",
"Increases the damage done by your offhand weapon by 20%.",
"Increases the damage done by your offhand weapon by 25%."
		];i++;		

//Improved Execute - Fury
rank[i] = [
"Reduces the Rage cost of your Execute ability by 2.",
"Reduces the Rage cost of your Execute ability by 5."
		];
i++;		

//Enrage - Fury
rank[i] = [
"Gives you a 5% melee damage bonus for 12 sec up to a maximum of 12 swings after being the victim of a critical strike.",
"Gives you a 10% melee damage bonus for 12 sec up to a maximum of 12 swings after being the victim of a critical strike.",
"Gives you a 15% melee damage bonus for 12 sec up to a maximum of 12 swings after being the victim of a critical strike.",
"Gives you a 20% melee damage bonus for 12 sec up to a maximum of 12 swings after being the victim of a critical strike.",
"Gives you a 25% melee damage bonus for 12 sec up to a maximum of 12 swings after being the victim of a critical strike."
		];
i++;

//Improved Slam - Fury

rank[i] = [
"Decreases the casting time of your Slam ability by 0.1 sec.",
"Decreases the casting time of your Slam ability by 0.2 sec.",
"Decreases the casting time of your Slam ability by 0.3 sec.",
"Decreases the casting time of your Slam ability by 0.4 sec.",
"Decreases the casting time of your Slam ability by 0.5 sec."
		];
i++;
		
//Death Wish - Fury
rank[i]=[
		"10 Rage<br><span style=text-align:left;float:left;>Instant</span><span style=text-align:right;float:right;>3 min cooldown</span><br>When activated, increases your physical damage by 20% and makes you immune to Fear effects, but lowers your armor and all resistances by 20%. Lasts 30 sec."
			];
i++;			
			
//Improved Intercept - Fury
rank[i]=[
"Reduces the cooldown of your Intercept ability by 5 sec.",
"Reduces the cooldown of your Intercept ability by 10 sec."
		];
i++;		
		
//Improved Berserker Rage - Fury
rank[i]=[
"The Berserker Rage ability will generate 5 rage when used.",
"The Berserker Rage ability will generate 10 rage when used."
		];
i++;		
		
//Flurry - Fury
rank[i]=[
"Increases your attack speed by 10% for your next 3 swings after dealing a critical strike.",
"Increases your attack speed by 15% for your next 3 swings after dealing a critical strike.",
"Increases your attack speed by 20% for your next 3 swings after dealing a critical strike.",
"Increases your attack speed by 25% for your next 3 swings after dealing a critical strike.",
"Increases your attack speed by 30% for your next 3 swings after dealing a critical strike."
		];
i++;		
		
//Bloodthirst - Fury
rank[i]=[
		"<span style=text-align:left;float:left;>30 Rage</span><span style=text-align:right;float:right;>5 yd range</span><br><span style=text-align:left;float:left;>Instant</span><span style=text-align:right;float:right;>6 sec cooldown</span><br>Instantly attack the target, causing damage equal to 40% of your attack power. In addition, the next 5 successful melee attacks will restore 10 health. This effect lasts 8 sec.<br><br>\
		&nbsp;Trainable Ranks Listed Below:<br>\
		&nbsp;Rank 2: 13 Health<br>\
		&nbsp;Rank 3: 17 Health<br>\
		&nbsp;Rank 4: 20 Health"
		];
i++;		










		
//Shield Specialization - Protection
rank[i]=[
"Increases your chance to block attacks with a shield by 1% and has a 20% chance to generate 1 rage when a block occurs.",
"Increases your chance to block attacks with a shield by 2% and has a 40% chance to generate 1 rage when a block occurs.",
"Increases your chance to block attacks with a shield by 3% and has a 60% chance to generate 1 rage when a block occurs.",
"Increases your chance to block attacks with a shield by 4% and has a 80% chance to generate 1 rage when a block occurs.",
"Increases your chance to block attacks with a shield by 5% and has a 100% chance to generate 1 rage when a block occurs."
		];
i++;		
		
//Anticipation - Protection
rank[i]=[
"Increases your Defense skill by 2.",
"Increases your Defense skill by 4.",
"Increases your Defense skill by 6.",
"Increases your Defense skill by 8.",
"Increases your Defense skill by 10."
		];
i++;		
		
//Improved Bloodrage - Protection
rank[i]=[
"Increases the instant Rage generated by your Bloodrage ability by 2.",
"Increases the instant Rage generated by your Bloodrage ability by 5."
		];
i++;		
		
//Toughness - Protection
rank[i]=[
"Increases your armor value from items by 2%.",
"Increases your armor value from items by 4%.",
"Increases your armor value from items by 6%.",
"Increases your armor value from items by 8%.",
"Increases your armor value from items by 10%."
		];
i++;		
		
//Iron Will - Protection
rank[i]=[
"Increases your chance to resist stun and charm effects by 3%.",
"Increases your chance to resist stun and charm effects by 6%.",
"Increases your chance to resist stun and charm effects by 9%.",
"Increases your chance to resist stun and charm effects by 12%.",
"Increases your chance to resist stun and charm effects by 15%."
		];
i++;		
		
//Last Stand - Protection
rank[i]=[
		"<span style=text-align:left;float:left;>Instant</span><span style=text-align:right;float:right;>10 min cooldown</span><br>When activated, this ability temporarily grants you 30% of your maximum hit points for 20 sec. After the effect expires, the hit points are lost."
		];
i++;		
		
//Improved Shield Block - Protection
rank[i]=[
"Allows your Shield Block ability to block an additional attack, and increases the duration by 0.5 sec.",
"Allows your Shield Block ability to block an additional attack, and increases the duration by 1 sec.",
"Allows your Shield Block ability to block an additional attack, and increases the duration by 2 sec."
		];
i++;		
		
//Improved Revenge - Protection
rank[i]=[
"Gives your Revenge ability a 15% chance to stun the target for 3 sec.",
"Gives your Revenge ability a 30% chance to stun the target for 3 sec.",
"Gives your Revenge ability a 45% chance to stun the target for 3 sec."
		];
i++;		
		
//Defiance - Protection
rank[i]=[
"Increases the threat generated by your attacks by 3% while in Defensive Stance.",
"Increases the threat generated by your attacks by 6% while in Defensive Stance.",
"Increases the threat generated by your attacks by 9% while in Defensive Stance.",
"Increases the threat generated by your attacks by 12% while in Defensive Stance.",
"Increases the threat generated by your attacks by 15% while in Defensive Stance."
		];
i++;		
		
//Improved Sunder Armor - Protection
rank[i]=[
"Reduces the cost of your Sunder Armor ability by 1 rage point.",
"Reduces the cost of your Sunder Armor ability by 2 rage points.",
"Reduces the cost of your Sunder Armor ability by 3 rage points."
		];
i++;	
		
//Improved Disarm - Protection
rank[i]=[
"Increases the duration of your Disarm ability by 1 secs.",
"Increases the duration of your Disarm ability by 2 secs.",
"Increases the duration of your Disarm ability by 3 secs."
		];
i++;	


//Improved Taunt - Protection
rank[i]=[
"Reduces the cooldown of your Taunt ability by 1 sec.",
"Reduces the cooldown of your Taunt ability by 2 sec."
		];
i++;	


//Improved Shield Wall - Protection
rank[i]=[
"Increases the effect duration of your Shield Wall ability by 3 secs.",
"Increases the effect duration of your Shield Wall ability by 5 secs."
		];
i++;	

//Concussion Blow - Protection
rank[i]=[
		"<span style=text-align:left;float:left;>15 Rage</span><span style=text-align:right;float:right;>5 yd range</span><br><span style=text-align:left;float:left;>Instant</span><span style=text-align:right;float:right;>45 sec cooldown</span><br>Stuns the opponent for 5 sec."
		];
i++;	

//Improved Shield Bash - Protection
rank[i]=[
"Gives your Shield Bash ability a 50% chance to silence the target for 3 sec.",
"Gives your Shield Bash ability a 100% chance to silence the target for 3 sec."
		];
i++;	

//One-Handed Weapon Specialization - Protection
rank[i]=[
"Increases the damage you deal with One-Handed Melee weapons by 2%.",
"Increases the damage you deal with One-Handed Melee weapons by 4%.",
"Increases the damage you deal with One-Handed Melee weapons by 6%.",
"Increases the damage you deal with One-Handed Melee weapons by 8%.",
"Increases the damage you deal with One-Handed Melee weapons by 10%."
		];
i++;	

//Shield Slam - Protection
rank[i]=[
		"<span style=text-align:left;float:left;>30 Rage</span><span style=text-align:right;float:right;>5 yd range</span><br><span style=text-align:left;float:left;>Instant</span><span style=text-align:right;float:right;>6 sec cooldown</span><br>Requires Shields<br>Slam the target with your shield, causing 225 to 235 damage, modified by your shield block value, and has a 50% chance of dispelling 1 magic effect on the target. Also causes a high amount of threat.<br><br>\
		&nbsp;Trainable Ranks Listed Below:<br>\
		&nbsp;Rank 2: 342-418 Damage<br>\
		&nbsp;Rank 3: 396-484 Damage<br>\
		&nbsp;Rank 4: 450-550 Damage"
		];
i++;	
		
//Protection Talents End^^
/*
     FILE ARCHIVED ON 11:56:58 Jul 20, 2006 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 20:22:21 Sep 08, 2021.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  exclusion.robots.policy: 0.239
  CDXLines.iter: 22.428 (3)
  LoadShardBlock: 113.134 (3)
  captures_list: 166.814
  PetaboxLoader3.datanode: 112.184 (4)
  exclusion.robots: 0.253
  load_resource: 181.12
  esindex: 0.026
  PetaboxLoader3.resolve: 156.238
  RedisCDXSource: 27.453
*/